theme: jekyll-theme-minimal
title: Sam Tebbs
description: Low-level developer and Computer Science MSci student at the University of Birmingham (graduating in June 2020)

footer_links:
        linkedin: samuel-tebbs-703152107
